# Vizualisation of data casos-de-dengue
source: [Conjunto de dados - Portal de Dados Abertos da Prefeitura do Recife](https://dados.recife.pe.gov.br/pt_BR/dataset/?tags=arbovirose)

- *dengue data*
- *only recife information*
  
We have 3 types of bairro info, 2 in code and 1 in names. If we find a way to map, we can change the granularity

In [50]:
import pandas as pd
from pathlib import Path

In [51]:
current_dir = Path(Path.cwd()).parent.parent
data_dir = current_dir / "data"
source_data_dir = data_dir / "source"
print(data_dir)

d:\pedro\Programacao\.Projetos\dengue_prediction\dengue_prediction\data

In [52]:

import re
import unicodedata
 
def show_columns(df, n_range = 7):
    df = list(df.columns)
    l = []
    range = n_range
    for c in df:
        if range == n_range:
            print(l)
            l = []
            range = 0
        range += 1
        l.append(c)
    print("\n")

def normalize_column(col):
    # tira acentos
    col = unicodedata.normalize("NFKD", col).encode("ascii", "ignore").decode("utf-8")
    # minúsculas
    col = col.lower()
    # troca qualquer coisa que não seja letra ou número por _
    col = re.sub(r"[^a-z0-9]+", "_", col)
    # remove _ no começo e no fim
    col = col.strip("_")
    return col

In [53]:
def prep_show(df):
    # remove coluns with more than 40% missing values
    df = df.loc[
        :, df.isnull().mean() < 0.4
    ]
    df.columns = [normalize_column(col) for col in df.columns]

    show_columns(df=df)
    print(f"porcentagem de valores ausentes:\n{(df.isnull().mean() * 100).sort_values(ascending=False)}%")
    return df

### 2013

In [54]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2013 = pd.read_csv(dengue_dir / "casos-de-dengue-2013.csv", sep=";")
df_2013 = prep_show(df_2013)
df_2013.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_digitacao']
['dt_transf_sm', 'nu_lote_vertical', 'dt_investigacao', 'tp_result_exame', 'tp_result_ns1', 'tp_result_isolamento', 'tp_result_rtpcr']
['tp_result_histopatologia', 'tp_result_imunohistoquimica', 'tp_classificacao_final', 'tp_criterio_confirmacao', 'tp_evolucao_caso', 'dt_encerramento', 'st_ocorreu_hospitalizacao']


porcentagem de valores ausentes:
tp_result_histopatologia       33.230102
tp_result_ns1                  32.548777
tp_result_isolamento           32.301022
tp_result_imunohistoquimica    32.301022
tp_result_rtpcr                31.991329
st_ocorreu_hospitalizacao      18.550635
tp_escolaridade                10.003097
dt_nascimento                   9.662434
tp_raca_cor                     4.800248
tp_result_exame                 2.570455
tp_zona_residencia              1.517498
tp_evolucao_caso                0.495509
nome_logradouro_residencia      0.402601
id_regional                     0.123877
nu_telefone_hospital            0.092908
dt_diagnostico_sintoma          0.000000
co_unidade_notificacao          0.000000
dt_notificacao                  0.000000
co_cid                          0.000000
nu_notificacao                  0.000000
tp_notificacao                  0.000000
co_municipio_notificacao        0.000000
co_uf_notificacao               0.000000
ds_semana_notificacao           0.000000
notificacao_ano                 0.000000
tp_sexo                         0.000000
nu_idade                        0.000000
co_pais_residencia              0.000000
no_bairro_residencia            0.000000
co_distrito_residencia          0.000000
co_bairro_residencia            0.000000
co_regional_residencia          0.000000
co_municipio_residencia         0.000000
tp_gestante                     0.000000
co_uf_residencia                0.000000
ds_semana_sintoma               0.000000
dt_transf_sm                    0.000000
nu_lote_vertical                0.000000
dt_investigacao                 0.000000
dt_digitacao                    0.000000
tp_classificacao_final          0.000000
tp_criterio_confirmacao         0.000000
dt_encerramento                 0.000000
dtype: float64%

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,tp_result_isolamento,tp_result_rtpcr,tp_result_histopatologia,tp_result_imunohistoquimica,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento,st_ocorreu_hospitalizacao,nu_telefone_hospital
0,1224587,2,A90,2013/01/04 00:00:00,201301,2013,26,261160,1497.0,3008002,...,4.0,4.0,4.0,4.0,5,1,1.0,2013/02/20 00:00:00,2.0,2013008.0
1,1411256,2,A90,2013/01/07 00:00:00,201302,2013,26,261160,1497.0,5540739,...,NaN,NaN,NaN,NaN,5,2,1.0,2013/02/18 00:00:00,9.0,2013008.0
2,1418852,2,A90,2013/02/20 00:00:00,201308,2013,26,261160,1497.0,6481876,...,NaN,NaN,NaN,NaN,5,2,1.0,2013/03/29 00:00:00,9.0,2013018.0
3,1292875,2,A90,2013/01/03 00:00:00,201301,2013,26,261160,1497.0,2517140,...,4.0,4.0,4.0,4.0,5,2,1.0,2013/01/25 00:00:00,2.0,2013004.0
4,1416160,2,A90,2013/01/07 00:00:00,201302,2013,26,261160,1497.0,3008002,...,4.0,NaN,NaN,4.0,5,2,1.0,2013/01/10 00:00:00,9.0,2013005.0

### 2014

In [55]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2014 = pd.read_csv(dengue_dir / "casos-de-dengue-2014.csv", sep=";")
df_2014 = prep_show(df_2014)
df_2014.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_digitacao']
['dt_transf_sm', 'nu_lote_vertical', 'dt_investigacao', 'tp_result_exame', 'tp_result_ns1', 'tp_result_isolamento', 'tp_result_rtpcr']
['tp_result_histopatologia', 'tp_result_imunohistoquimica', 'tp_classificacao_final', 'tp_criterio_confirmacao', 'tp_evolucao_caso', 'dt_encerramento', 'st_ocorreu_hospitalizacao']


porcentagem de valores ausentes:
tp_result_histopatologia       39.848993
tp_result_rtpcr                37.919463
tp_result_imunohistoquimica    37.919463
tp_result_isolamento           35.989933
tp_result_ns1                  31.543624
st_ocorreu_hospitalizacao      19.463087
tp_escolaridade                11.073826
tp_result_exame                 7.634228
dt_nascimento                   6.291946
tp_zona_residencia              2.684564
tp_raca_cor                     2.516779
tp_evolucao_caso                1.845638
nome_logradouro_residencia      0.671141
co_distrito_residencia          0.251678
id_regional                     0.083893
nu_telefone_hospital            0.083893
co_unidade_notificacao          0.000000
dt_diagnostico_sintoma          0.000000
co_cid                          0.000000
nu_notificacao                  0.000000
tp_notificacao                  0.000000
co_municipio_notificacao        0.000000
co_uf_notificacao               0.000000
ds_semana_notificacao           0.000000
notificacao_ano                 0.000000
dt_notificacao                  0.000000
tp_sexo                         0.000000
co_pais_residencia              0.000000
no_bairro_residencia            0.000000
co_regional_residencia          0.000000
co_bairro_residencia            0.000000
co_municipio_residencia         0.000000
nu_idade                        0.000000
tp_gestante                     0.000000
co_uf_residencia                0.000000
ds_semana_sintoma               0.000000
dt_transf_sm                    0.000000
nu_lote_vertical                0.000000
dt_investigacao                 0.000000
dt_digitacao                    0.000000
tp_classificacao_final          0.000000
tp_criterio_confirmacao         0.000000
dt_encerramento                 0.000000
dtype: float64%

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,tp_result_isolamento,tp_result_rtpcr,tp_result_histopatologia,tp_result_imunohistoquimica,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento,st_ocorreu_hospitalizacao,nu_telefone_hospital
0,1552181,2,A90,2014/01/17 00:00:00,201403,2014,26,261160,1497.0,6481876,...,NaN,NaN,NaN,NaN,5,2,1.0,2014/01/20 00:00:00,9.0,2014004.0
1,1558049,2,A90,2014/04/10 00:00:00,201415,2014,26,261160,1497.0,20516,...,4.0,4.0,4.0,NaN,5,2,1.0,2014/06/25 00:00:00,2.0,2014026.0
2,1553818,2,A90,2014/01/07 00:00:00,201402,2014,26,261160,1497.0,2802783,...,NaN,NaN,NaN,NaN,5,1,1.0,2014/02/14 00:00:00,NaN,2014008.0
3,1552193,2,A90,2014/01/07 00:00:00,201402,2014,26,261160,1497.0,6726852,...,NaN,NaN,NaN,NaN,1,2,1.0,2014/01/28 00:00:00,2.0,2014005.0
4,1552185,2,A90,2014/01/17 00:00:00,201403,2014,26,261160,1497.0,6481876,...,NaN,NaN,NaN,NaN,5,2,1.0,2014/01/20 00:00:00,2.0,2014004.0

### 2015

In [56]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2015 = pd.read_csv(dengue_dir / "casos-de-dengue-2015.csv", sep=",")
df_2015 = prep_show(df_2015)
df_2015.head()

C:\Users\pedro\AppData\Local\Temp\ipykernel_36900\2866692290.py:2: DtypeWarning: Columns (30,52,96,112) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2015 = pd.read_csv(dengue_dir / "casos-de-dengue-2015.csv", sep=",")

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_investigacao']


porcentagem de valores ausentes:
tp_result_exame               39.052552
tp_escolaridade               33.487672
tp_raca_cor                   24.166570
co_distrito_residencia        12.521704
tp_evolucao_caso              12.235212
tp_zona_residencia             9.057761
tp_criterio_confirmacao        8.814678
dt_investigacao                3.747540
nome_logradouro_residencia     2.167496
co_bairro_residencia           2.095150
dt_nascimento                  1.655284
no_bairro_residencia           0.795810
dt_encerramento                0.763977
tp_classificacao_final         0.156268
tp_sexo                        0.141799
co_uf_residencia               0.141799
id_regional                    0.136011
tp_gestante                    0.136011
co_cid                         0.133117
dt_diagnostico_sintoma         0.133117
co_unidade_notificacao         0.133117
nu_idade                       0.133117
notificacao_ano                0.133117
co_uf_notificacao              0.133117
co_municipio_notificacao       0.133117
ds_semana_notificacao          0.133117
dt_notificacao                 0.133117
tp_notificacao                 0.133117
ds_semana_sintoma              0.133117
co_municipio_residencia        0.133117
co_regional_residencia         0.133117
co_pais_residencia             0.133117
nu_notificacao                 0.000000
dtype: float64%

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,no_bairro_residencia,nome_logradouro_residencia,tp_zona_residencia,co_pais_residencia,dt_investigacao,tp_result_exame,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento
0,2126258,2.0,A90,2015-12-10,201549.0,2015.0,26.0,261160.0,1497.0,930.0,...,IMBIRIBEIRA,R NOSSA SENHORA DO CARMO,1.0,1.0,2015-12-10,NaN,8.0,NaN,NaN,2016-02-09
1,1562314,2.0,A90,2015-01-21,201503.0,2015.0,26.0,261160.0,1497.0,6468918.0,...,SANTO AMARO,RUA FREI CASSIMIRO,1.0,1.0,2015-01-21,NaN,5.0,2.0,1.0,2015-03-20
2,1758636,2.0,A90,2015-01-06,201501.0,2015.0,26.0,260960.0,1497.0,2345021.0,...,SANTO AMARO,RUA CAMPO DA VOVOZINHA,1.0,1.0,2015-02-02,NaN,5.0,2.0,1.0,2015-02-03
3,2127412,2.0,A90,2015-10-26,201543.0,2015.0,26.0,261160.0,1497.0,20516.0,...,SANTO AMARO,RUA TUPINIQUIM,1.0,1.0,2015-11-16,NaN,10.0,2.0,1.0,2015-11-16
4,1562589,2.0,A90,2015-01-19,201503.0,2015.0,26.0,261160.0,1497.0,6703437.0,...,SANTO AMARO,RUA JOAQUIM RABELO,1.0,1.0,2015-03-03,1.0,10.0,1.0,1.0,2015-03-16

### 2016

In [57]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2016 = pd.read_csv(dengue_dir / "casos-de-dengue-2016.csv", sep=";")
df_2016 = prep_show(df_2016)
df_2016.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_investigacao']
['febre', 'mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas']
['conjutivite', 'artrite', 'artralgia', 'petequia_n', 'leucopenia', 'laco', 'dor_retro']
['diabetes', 'hematolog', 'hepatopat', 'renal', 'hipertensao', 'acido_pept', 'auto_imune']


porcentagem de valores ausentes:
hepatopat                     32.151300
auto_imune                    32.151300
acido_pept                    32.151300
hipertensao                   32.151300
renal                         32.151300
artralgia                     32.151300
petequia_n                    32.151300
leucopenia                    32.151300
laco                          32.151300
dor_retro                     32.151300
diabetes                      32.151300
hematolog                     32.151300
artrite                       32.151300
mialgia                       32.151300
cefaleia                      32.151300
exantema                      32.151300
vomito                        32.151300
nausea                        32.151300
dor_costas                    32.151300
conjutivite                   32.151300
febre                         32.151300
tp_escolaridade               29.040404
co_distrito_residencia        18.805072
tp_zona_residencia            14.307973
tp_evolucao_caso              13.964109
tp_raca_cor                    8.053944
tp_criterio_confirmacao        8.000215
co_bairro_residencia           4.663658
dt_investigacao                3.562218
dt_nascimento                  3.486998
nome_logradouro_residencia     2.170643
dt_encerramento                2.100795
no_bairro_residencia           1.816033
tp_classificacao_final         0.123576
tp_gestante                    0.016119
tp_sexo                        0.005373
co_uf_residencia               0.005373
id_regional                    0.005373
co_municipio_residencia        0.000000
co_regional_residencia         0.000000
notificacao_ano                0.000000
co_municipio_notificacao       0.000000
co_unidade_notificacao         0.000000
nu_idade                       0.000000
ds_semana_sintoma              0.000000
co_uf_notificacao              0.000000
co_cid                         0.000000
dt_notificacao                 0.000000
nu_notificacao                 0.000000
tp_notificacao                 0.000000
ds_semana_notificacao          0.000000
dt_diagnostico_sintoma         0.000000
co_pais_residencia             0.000000
dtype: float64%

C:\Users\pedro\AppData\Local\Temp\ipykernel_36900\2945118260.py:2: DtypeWarning: Columns (54,112) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016 = pd.read_csv(dengue_dir / "casos-de-dengue-2016.csv", sep=";")

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,hematolog,hepatopat,renal,hipertensao,acido_pept,auto_imune,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento
0,2161375,2,A90,2016-01-21,201603,2016,26,261160,1497.0,6488315,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0,9.0,2016-01-27
1,2154420,2,A90,2016-01-08,201601,2016,26,261160,1497.0,28665,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2016-03-05
2,2171335,2,A90,2016-01-22,201603,2016,26,261160,1497.0,1120,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,2016-03-23
3,2156090,2,A90,2016-01-07,201601,2016,26,261160,1497.0,531,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,2016-03-04
4,2588634,2,A90,2016-01-07,201601,2016,26,261160,1497.0,5396670,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2016-03-02

### 2017

In [58]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2017 = pd.read_csv(dengue_dir / "casos-de-dengue-2017.csv", sep=";")
df_2017 = prep_show(df_2017)
df_2017.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_investigacao']
['febre', 'mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas']
['conjutivite', 'artrite', 'artralgia', 'petequia_n', 'leucopenia', 'laco', 'dor_retro']
['diabetes', 'hematolog', 'hepatopat', 'renal', 'hipertensao', 'acido_pept', 'auto_imune']


porcentagem de valores ausentes:
tp_escolaridade               6.519967
tp_zona_residencia            5.827221
nome_logradouro_residencia    1.100244
dt_nascimento                 0.977995
tp_evolucao_caso              0.325998
tp_criterio_confirmacao       0.162999
co_bairro_residencia          0.040750
co_distrito_residencia        0.040750
no_bairro_residencia          0.040750
tp_gestante                   0.040750
ds_semana_notificacao         0.000000
co_municipio_notificacao      0.000000
co_uf_notificacao             0.000000
ds_semana_sintoma             0.000000
dt_notificacao                0.000000
co_cid                        0.000000
notificacao_ano               0.000000
id_regional                   0.000000
co_unidade_notificacao        0.000000
tp_notificacao                0.000000
nu_notificacao                0.000000
co_regional_residencia        0.000000
co_municipio_residencia       0.000000
co_uf_residencia              0.000000
tp_raca_cor                   0.000000
nu_idade                      0.000000
tp_sexo                       0.000000
dt_diagnostico_sintoma        0.000000
co_pais_residencia            0.000000
mialgia                       0.000000
cefaleia                      0.000000
exantema                      0.000000
vomito                        0.000000
nausea                        0.000000
dor_costas                    0.000000
dt_investigacao               0.000000
febre                         0.000000
artrite                       0.000000
conjutivite                   0.000000
artralgia                     0.000000
petequia_n                    0.000000
dor_retro                     0.000000
diabetes                      0.000000
leucopenia                    0.000000
laco                          0.000000
hepatopat                     0.000000
hematolog                     0.000000
renal                         0.000000
hipertensao                   0.000000
auto_imune                    0.000000
acido_pept                    0.000000
tp_classificacao_final        0.000000
dt_encerramento               0.000000
dtype: float64%

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,hematolog,hepatopat,renal,hipertensao,acido_pept,auto_imune,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento
0,2634048,2,A90,2017-01-09,201702,2017,26,261160,1497,604,...,2,2,2,2,2,2,10,2.0,1.0,2017-03-05
1,2634863,2,A90,2017-01-19,201703,2017,26,261160,1497,6508960,...,2,2,2,2,2,2,10,2.0,1.0,2017-02-20
2,2634610,2,A90,2017-01-03,201701,2017,26,261160,1497,5540739,...,2,2,2,2,2,2,10,2.0,1.0,2017-01-20
3,2615378,2,A90,2017-01-06,201701,2017,26,261160,1497,701,...,2,2,2,2,2,2,5,1.0,1.0,2017-02-28
4,2593019,2,A90,2017-01-04,201701,2017,26,261160,1497,6488315,...,2,2,2,2,2,2,10,2.0,1.0,2017-02-16

### 2018

In [59]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2018 = pd.read_csv(dengue_dir / "casos-de-dengue-2018.csv", sep=";")
df_2018 = prep_show(df_2018)
df_2018.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'co_pais_residencia', 'dt_investigacao', 'febre']
['mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas', 'conjutivite']
['artrite', 'artralgia', 'petequia_n', 'leucopenia', 'laco', 'dor_retro', 'diabetes']
['hematolog', 'hepatopat', 'renal', 'hipertensao', 'acido_pept', 'auto_imune', 'st_ocorreu_hospitalizacao']


porcentagem de valores ausentes:
st_ocorreu_hospitalizacao     38.481578
tp_escolaridade                9.639003
dt_nascimento                  2.009676
nome_logradouro_residencia     1.600298
tp_evolucao_caso               0.967622
co_bairro_residencia           0.521027
co_distrito_residencia         0.483811
tp_criterio_confirmacao        0.446595
no_bairro_residencia           0.297730
cefaleia                       0.148865
vomito                         0.148865
exantema                       0.148865
dor_costas                     0.148865
dt_investigacao                0.148865
mialgia                        0.148865
febre                          0.148865
artrite                        0.148865
nausea                         0.148865
conjutivite                    0.148865
artralgia                      0.148865
renal                          0.148865
auto_imune                     0.148865
hepatopat                      0.148865
hematolog                      0.148865
petequia_n                     0.148865
diabetes                       0.148865
leucopenia                     0.148865
laco                           0.148865
dor_retro                      0.148865
acido_pept                     0.148865
hipertensao                    0.148865
tp_gestante                    0.074432
id_regional                    0.037216
tp_sexo                        0.037216
co_uf_residencia               0.037216
tp_raca_cor                    0.037216
ds_semana_notificacao          0.000000
co_regional_residencia         0.000000
co_municipio_residencia        0.000000
nu_idade                       0.000000
notificacao_ano                0.000000
co_municipio_notificacao       0.000000
co_unidade_notificacao         0.000000
dt_diagnostico_sintoma         0.000000
ds_semana_sintoma              0.000000
co_uf_notificacao              0.000000
co_cid                         0.000000
dt_notificacao                 0.000000
nu_notificacao                 0.000000
tp_notificacao                 0.000000
co_pais_residencia             0.000000
tp_classificacao_final         0.000000
dt_encerramento                0.000000
dtype: float64%

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,hepatopat,renal,hipertensao,acido_pept,auto_imune,st_ocorreu_hospitalizacao,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento
0,3143497,2,A90,2018-01-08,201802,2018,26,261160,1497.0,6726852,...,2.0,2.0,2.0,2.0,2.0,2.0,10,2.0,1.0,2018-06-01
1,2838480,2,A90,2018-01-19,201803,2018,26,261160,1497.0,6481876,...,2.0,2.0,2.0,2.0,2.0,2.0,5,2.0,1.0,2018-02-19
2,2860913,2,A90,2018-02-20,201808,2018,26,261160,1497.0,6530389,...,2.0,2.0,2.0,2.0,2.0,NaN,10,2.0,1.0,2018-02-20
3,2921081,2,A90,2018-01-04,201801,2018,26,261160,1497.0,981,...,2.0,2.0,2.0,2.0,2.0,2.0,10,2.0,1.0,2018-01-04
4,2855974,2,A90,2018-01-04,201801,2018,26,261160,1497.0,531,...,2.0,2.0,2.0,2.0,2.0,2.0,10,2.0,1.0,2018-02-22

### 2019

In [65]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2019 = pd.read_csv(dengue_dir / "casos-de-dengue-2019.csv", sep=",")
df_2019 = prep_show(df_2019)
df_2019.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_investigacao']
['febre', 'mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas']
['conjutivite', 'artrite', 'artralgia', 'petequia_n', 'leucopenia', 'laco', 'dor_retro']
['diabetes', 'hematolog', 'hepatopat', 'renal', 'hipertensao', 'acido_pept', 'auto_imune']


porcentagem de valores ausentes:
st_ocorreu_hospitalizacao     35.454297
co_distrito_residencia        13.683634
tp_escolaridade               11.973180
tp_evolucao_caso               9.646962
tp_criterio_confirmacao        8.045977
tp_zona_residencia             4.529283
dt_nascimento                  3.024083
co_bairro_residencia           2.367269
dt_investigacao                2.066229
exantema                       2.052545
cefaleia                       2.052545
artrite                        2.052545
conjutivite                    2.052545
dor_costas                     2.052545
febre                          2.052545
mialgia                        2.052545
vomito                         2.052545
artralgia                      2.052545
nausea                         2.052545
hematolog                      2.052545
hepatopat                      2.052545
renal                          2.052545
auto_imune                     2.052545
acido_pept                     2.052545
hipertensao                    2.052545
petequia_n                     2.052545
diabetes                       2.052545
leucopenia                     2.052545
laco                           2.052545
dor_retro                      2.052545
nome_logradouro_residencia     1.984127
no_bairro_residencia           1.108374
id_regional                    0.109469
tp_gestante                    0.109469
tp_notificacao                 0.082102
dt_notificacao                 0.082102
notificacao_ano                0.082102
nu_idade                       0.082102
co_uf_notificacao              0.082102
co_regional_residencia         0.082102
co_uf_residencia               0.082102
co_municipio_residencia        0.082102
tp_sexo                        0.082102
dt_diagnostico_sintoma         0.082102
ds_semana_sintoma              0.082102
tp_raca_cor                    0.082102
ds_semana_notificacao          0.082102
co_municipio_notificacao       0.082102
co_unidade_notificacao         0.082102
co_cid                         0.082102
tp_classificacao_final         0.082102
co_pais_residencia             0.082102
dt_encerramento                0.082102
nu_notificacao                 0.000000
dtype: float64%

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,hepatopat,renal,hipertensao,acido_pept,auto_imune,st_ocorreu_hospitalizacao,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento
0,3163014,2.0,A90,2019-01-04,201901.0,2019.0,26.0,261160.0,1497.0,1015.0,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2019-03-03
1,3257708,2.0,A90,2019-05-21,201921.0,2019.0,26.0,261160.0,1497.0,1120.0,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,1.0,2019-06-11
2,3173295,2.0,A90,2019-01-09,201902.0,2019.0,26.0,261160.0,1497.0,930.0,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2019-04-30
3,3174753,2.0,A90,2019-01-03,201901.0,2019.0,26.0,261160.0,1497.0,671.0,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2019-01-24
4,3174754,2.0,A90,2019-01-02,201901.0,2019.0,26.0,261160.0,1497.0,671.0,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,1.0,2019-01-18

### 2020

In [67]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2020 = pd.read_csv(dengue_dir / "casos-de-dengue-2020.csv", sep=";")
df_2020 = prep_show(df_2020)
df_2020.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_investigacao']
['febre', 'mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas']
['conjutivite', 'artrite', 'artralgia', 'petequia_n', 'leucopenia', 'laco', 'dor_retro']
['diabetes', 'hematolog', 'hepatopat', 'renal', 'hipertensao', 'acido_pept', 'auto_imune']


porcentagem de valores ausentes:
tp_escolaridade               17.542373
tp_evolucao_caso               4.774011
tp_criterio_confirmacao        3.474576
tp_zona_residencia             2.966102
nome_logradouro_residencia     1.751412
dt_nascimento                  1.468927
dt_encerramento                1.016949
exantema                       0.310734
cefaleia                       0.310734
mialgia                        0.310734
conjutivite                    0.310734
dor_costas                     0.310734
nausea                         0.310734
co_bairro_residencia           0.310734
dt_investigacao                0.310734
febre                          0.310734
artrite                        0.310734
vomito                         0.310734
diabetes                       0.310734
hematolog                      0.310734
hepatopat                      0.310734
auto_imune                     0.310734
acido_pept                     0.310734
hipertensao                    0.310734
artralgia                      0.310734
dor_retro                      0.310734
petequia_n                     0.310734
leucopenia                     0.310734
laco                           0.310734
renal                          0.310734
no_bairro_residencia           0.282486
co_distrito_residencia         0.141243
id_regional                    0.084746
tp_classificacao_final         0.028249
tp_gestante                    0.028249
co_regional_residencia         0.000000
ds_semana_notificacao          0.000000
nu_notificacao                 0.000000
co_municipio_residencia        0.000000
co_uf_residencia               0.000000
tp_raca_cor                    0.000000
nu_idade                       0.000000
tp_sexo                        0.000000
dt_diagnostico_sintoma         0.000000
ds_semana_sintoma              0.000000
notificacao_ano                0.000000
co_uf_notificacao              0.000000
co_unidade_notificacao         0.000000
co_municipio_notificacao       0.000000
tp_notificacao                 0.000000
co_cid                         0.000000
dt_notificacao                 0.000000
co_pais_residencia             0.000000
dtype: float64%

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,hematolog,hepatopat,renal,hipertensao,acido_pept,auto_imune,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento
0,3545397,2,A90,2020-01-01,202001,2020,26,260790,1497.0,6618464,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,1.0,2020-03-02
1,3507054,2,A90,2020-01-01,202001,2020,26,261160,1497.0,671,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2020-01-20
2,3520539,2,A90,2020-01-02,202001,2020,26,261160,1497.0,7958838,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2020-02-10
3,3521380,2,A90,2020-01-03,202001,2020,26,261160,1497.0,6530389,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2020-01-23
4,3516940,2,A90,2020-01-03,202001,2020,26,261160,1497.0,2352516,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,1.0,2020-01-22

### 2021

In [68]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2021 = pd.read_csv(dengue_dir / "casos-de-dengue-2021.csv", sep=";")
df_2021 = prep_show(df_2021)
df_2021.head()

[]
['nu_notific', 'tp_not', 'id_agravo', 'dt_notific', 'sem_not', 'nu_ano', 'sg_uf_not']
['id_municip', 'id_regiona', 'id_unidade', 'dt_sin_pri', 'sem_pri', 'dt_nasc', 'nu_idade_n']
['cs_sexo', 'cs_gestant', 'cs_raca', 'cs_escol_n', 'sg_uf', 'id_mn_resi', 'id_rg_resi']
['id_distrit', 'id_bairro', 'nm_bairro', 'nm_logrado', 'cs_zona', 'id_pais', 'dt_invest']
['febre', 'mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas']
['conjuntvit', 'artrite', 'artralgia', 'petequia_n', 'leucopenia', 'laco', 'dor_retro']
['diabetes', 'hematolog', 'hepatopat', 'renal', 'hipertensa', 'acido_pept', 'auto_imune']


porcentagem de valores ausentes:
hospitaliz    39.741237
cs_escol_n    15.801064
cs_zona        5.184438
dt_nasc        4.184254
nm_logrado     1.743439
cs_gestant     0.064232
criterio       0.009176
id_regiona     0.009176
id_distrit     0.009176
evolucao       0.009176
nu_ano         0.000000
sem_not        0.000000
dt_notific     0.000000
sg_uf_not      0.000000
nu_idade_n     0.000000
sem_pri        0.000000
dt_sin_pri     0.000000
id_agravo      0.000000
tp_not         0.000000
id_unidade     0.000000
id_municip     0.000000
nu_notific     0.000000
id_rg_resi     0.000000
id_mn_resi     0.000000
sg_uf          0.000000
cs_raca        0.000000
cs_sexo        0.000000
id_pais        0.000000
nm_bairro      0.000000
id_bairro      0.000000
cefaleia       0.000000
exantema       0.000000
vomito         0.000000
nausea         0.000000
dor_costas     0.000000
dt_invest      0.000000
febre          0.000000
mialgia        0.000000
artralgia      0.000000
artrite        0.000000
conjuntvit     0.000000
petequia_n     0.000000
diabetes       0.000000
leucopenia     0.000000
laco           0.000000
dor_retro      0.000000
renal          0.000000
hepatopat      0.000000
hematolog      0.000000
hipertensa     0.000000
auto_imune     0.000000
acido_pept     0.000000
classi_fin     0.000000
dt_encerra     0.000000
dtype: float64%

0       IBURA
1       IBURA
2       IBURA
3       IBURA
4    ESTANCIA
Name: nm_bairro, dtype: object

In [63]:
dengue_dir = source_data_dir / "dengue_data/Recife"
df_2016 = pd.read_csv(dengue_dir / "casos-de-dengue-2016.csv", sep=";")
df_2016 = prep_show(df_2016)
df_2016.head()

[]
['nu_notificacao', 'tp_notificacao', 'co_cid', 'dt_notificacao', 'ds_semana_notificacao', 'notificacao_ano', 'co_uf_notificacao']
['co_municipio_notificacao', 'id_regional', 'co_unidade_notificacao', 'dt_diagnostico_sintoma', 'ds_semana_sintoma', 'dt_nascimento', 'nu_idade']
['tp_sexo', 'tp_gestante', 'tp_raca_cor', 'tp_escolaridade', 'co_uf_residencia', 'co_municipio_residencia', 'co_regional_residencia']
['co_distrito_residencia', 'co_bairro_residencia', 'no_bairro_residencia', 'nome_logradouro_residencia', 'tp_zona_residencia', 'co_pais_residencia', 'dt_investigacao']
['febre', 'mialgia', 'cefaleia', 'exantema', 'vomito', 'nausea', 'dor_costas']
['conjutivite', 'artrite', 'artralgia', 'petequia_n', 'leucopenia', 'laco', 'dor_retro']
['diabetes', 'hematolog', 'hepatopat', 'renal', 'hipertensao', 'acido_pept', 'auto_imune']


porcentagem de valores ausentes:
hepatopat                     32.151300
auto_imune                    32.151300
acido_pept                    32.151300
hipertensao                   32.151300
renal                         32.151300
artralgia                     32.151300
petequia_n                    32.151300
leucopenia                    32.151300
laco                          32.151300
dor_retro                     32.151300
diabetes                      32.151300
hematolog                     32.151300
artrite                       32.151300
mialgia                       32.151300
cefaleia                      32.151300
exantema                      32.151300
vomito                        32.151300
nausea                        32.151300
dor_costas                    32.151300
conjutivite                   32.151300
febre                         32.151300
tp_escolaridade               29.040404
co_distrito_residencia        18.805072
tp_zona_residencia            14.307973
tp_evolucao_caso              13.964109
tp_raca_cor                    8.053944
tp_criterio_confirmacao        8.000215
co_bairro_residencia           4.663658
dt_investigacao                3.562218
dt_nascimento                  3.486998
nome_logradouro_residencia     2.170643
dt_encerramento                2.100795
no_bairro_residencia           1.816033
tp_classificacao_final         0.123576
tp_gestante                    0.016119
tp_sexo                        0.005373
co_uf_residencia               0.005373
id_regional                    0.005373
co_municipio_residencia        0.000000
co_regional_residencia         0.000000
notificacao_ano                0.000000
co_municipio_notificacao       0.000000
co_unidade_notificacao         0.000000
nu_idade                       0.000000
ds_semana_sintoma              0.000000
co_uf_notificacao              0.000000
co_cid                         0.000000
dt_notificacao                 0.000000
nu_notificacao                 0.000000
tp_notificacao                 0.000000
ds_semana_notificacao          0.000000
dt_diagnostico_sintoma         0.000000
co_pais_residencia             0.000000
dtype: float64%

C:\Users\pedro\AppData\Local\Temp\ipykernel_36900\2945118260.py:2: DtypeWarning: Columns (54,112) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2016 = pd.read_csv(dengue_dir / "casos-de-dengue-2016.csv", sep=";")

,nu_notificacao,tp_notificacao,co_cid,dt_notificacao,ds_semana_notificacao,notificacao_ano,co_uf_notificacao,co_municipio_notificacao,id_regional,co_unidade_notificacao,...,hematolog,hepatopat,renal,hipertensao,acido_pept,auto_imune,tp_classificacao_final,tp_criterio_confirmacao,tp_evolucao_caso,dt_encerramento
0,2161375,2,A90,2016-01-21,201603,2016,26,261160,1497.0,6488315,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,2.0,9.0,2016-01-27
1,2154420,2,A90,2016-01-08,201601,2016,26,261160,1497.0,28665,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2016-03-05
2,2171335,2,A90,2016-01-22,201603,2016,26,261160,1497.0,1120,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,2016-03-23
3,2156090,2,A90,2016-01-07,201601,2016,26,261160,1497.0,531,...,2.0,2.0,2.0,2.0,2.0,2.0,5.0,2.0,NaN,2016-03-04
4,2588634,2,A90,2016-01-07,201601,2016,26,261160,1497.0,5396670,...,2.0,2.0,2.0,2.0,2.0,2.0,10.0,2.0,1.0,2016-03-02